stages:
- test
- push

test:
  stage: test
  image: harbottle/puppet-mattermost:latest
  script:
    - bundle exec rake spec

push:
  stage: push
  image: harbottle/puppet-mattermost:latest
  only:
    - master@harbottle/puppet-mattermost
  when: manual
  script:
    - rm -f Vagrantfile
    - rm -rf vagrant
    - bundle exec rake module:push
