#!/bin/bash

wget 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=<%= @geoip_key %>&suffix=tar.gz' -O geoip.tar.gz

tar zxvf geoip.tar.gz

mv GeoLite2-Country_*/GeoLite2-Country.mmdb /root/private/files/geoip/GeoLite2-Country.mmdb

git -C /root/private add . && git -C /root/private commit -m "GeoIPUpdate" && git -C /root/private push

rm -rf GeoLite2-Country_20* && rm geoip.tar.gz
