#! /usr/bin/python3
# This script fetches domains from Cloudflare for SaaS, and also domains from the WikiDiscover API, and the redirect domains from the repo's manual redirects file.
# It compares the two lists, writes the results to files, generates redirects.yaml, and pushes changes to a Git repository.

import sys
import requests
import yaml
import os
import subprocess
import argparse
from datetime import datetime, timedelta, timezone

# Variables for output files and proxy settings
CLOUDFLARE_OUTPUT = "cloudflare_domains"
WIKIDISCOVER_OUTPUT = "wikidiscover_output.yaml"
LOG_FILE = "domain_comparisons"
REDIRECTS_OUTPUT_FILE = "redirects.yaml"
REDIRECTS_MANUAL_FILE = "redirects_manual.yaml"
REDIRECTS_AUTO_FILE = "redirects_auto.yaml"
# Minimum amount of time to wait before redirecting a domain
REDIRECT_WAIT_HOURS = 24
REDIRECTS_HEADER = (
    "# Auto-generated by listdomains.py in puppet. Do not edit directly. Your changes will be lost.\n"
    "# Add redirects to redirects_manual.yaml instead.\n"
)
REDIRECTS_AUTO_HEADER = (
    "# Auto-generated by listdomains.py in puppet. Do not edit directly. Your changes will be lost.\n"
    "# Tracks every domain currently detected as configured in both Cloudflare and WikiDiscover.\n"
)
EXEMPT_DOMAINS = ["analytics.wikitide.net", "grafana.wikitide.net", "monitoring.wikitide.net", "orain.org", "phorge-static.wikitide.net",
    "static.wikitide.net", "wikitide.com", "www.orain.org"]
PROXY = "http://bastion.fsslc.wtnet:8080"
proxies = {"http": PROXY, "https": PROXY}

# Cloudflare credentials and headers
CLOUDFLARE_API_TOKEN = "<%= @cloudflare_api_token %>"
CLOUDFLARE_ZONE_ID = "<%= @cloudflare_zone_id %>"
CLOUDFLARE_API_URL = f"https://api.cloudflare.com/client/v4/zones/{CLOUDFLARE_ZONE_ID}/custom_hostnames"

cf_headers = {
    "Authorization": f"Bearer {CLOUDFLARE_API_TOKEN}",
    "X-Auth-Key": f"{CLOUDFLARE_API_TOKEN}",
    "Content-Type": "application/json",
    "User-Agent": "wikitide/listdomains.py (operated by WikiTide Foundation Technology Team - https://wikitide.org)"
}


def get_cloudflare_domains(quiet=False):
    all_domains = []
    page = 1
    # 50 domains per page is the maximum allowed by Cloudflare API
    # We will paginate through all results until we get an empty page
    per_page = 50
    while True:
        resp = requests.get(f"{CLOUDFLARE_API_URL}?page={page}&per_page={per_page}", headers=cf_headers, proxies=proxies)
        resp.raise_for_status()
        data = resp.json()
        result = data.get("result", [])
        if not result:
            break
        for entry in result:
            hostname = entry.get("hostname")
            if hostname:
                all_domains.append(hostname)
        if not quiet:
            print(f"Fetched {len(all_domains)} total domains from Cloudflare (page {page})...")
        page += 1
    return sorted(set(all_domains))


def get_wikidiscover_data():
    url = 'https://meta.miraheze.org/w/api.php'

    # Headers for the WikiDiscover API request
    headers = {
        "User-Agent": "wikitide/listdomains.py (operated by WikiTide Foundation Technology Team - https://wikitide.org)"
    }
    params = {
        'action': 'query',
        'format': 'json',
        'list': 'wikidiscover',
        'wdcustomurl': 'true',
        'wdprop': 'url',
        'wdlimit': '500'
    }

    yaml_output = {}
    domain_list = []
    offset = 0

    while True:
        if offset > 0:
            params['wdoffset'] = str(offset)

        response = requests.get(url, headers=headers, params=params, proxies=proxies)
        response.raise_for_status()

        result = response.json().get('query', {}).get('wikidiscover', {})
        wikis_data = result.get('wikis', {})
        count = result.get('count', 0)

        for dbname, info in wikis_data.items():
            wiki_url = info.get('url')
            if dbname.endswith("wiki") and wiki_url:
                yaml_output[dbname] = wiki_url
                domain = wiki_url.split("//")[1]
                domain_list.append(domain)

        if count == 0 or len(wikis_data) == 0:
            break

        print(f"Fetched {len(yaml_output)} wikis so far (offset: {offset})...")
        offset += len(wikis_data)

    return yaml_output, sorted(set(domain_list))


def load_yaml_file(file: str, expect_exist: bool = True) -> dict:
    if not os.path.exists(file):
        if expect_exist:
            raise FileNotFoundError(f"File {file} does not exist")
        return {}

    with open(file) as f:
        return yaml.safe_load(f) or {}


def get_domains_of(entries: dict) -> set[str]:
    """
    When blacklisting domains, both the original URL and the redirect are retrieved just to be safe.
    """
    domains = set()
    for entry in entries.values():
        domains.add(entry["url"])
        redirect = entry.get("redirect")
        if redirect:
            domains.add(redirect)
    return domains


def get_auto_redirect_candidate_domains(cf_domains: list[str], wd_domains: list[str], manual_domains: set[str]) -> set[str]:
    excluded = manual_domains | set(EXEMPT_DOMAINS)
    return (set(cf_domains) & set(wd_domains)) - excluded


def update_auto_redirects(existing_auto_redirects: dict, candidate_domains: set[str], wd_yaml: dict, now: datetime, 
                          manual_domains: set[str]) -> dict:
    domain_to_dbname: dict[str, str] = {url.split("//")[1]: dbname for dbname, url in wd_yaml.items()}

    updated = {}
    for domain in sorted(candidate_domains):
        dbname = domain_to_dbname.get(domain)
        if not dbname:
            continue
        # Only supports miraheze.org. Wikitide should be manually redirected.
        url = f"{dbname.removesuffix('wiki')}.miraheze.org"
        if url in manual_domains:
            # There is duplication removal for the target custom domain, but not the source MH domain, so we remove it here.
            continue
        key = f"{dbname}_autoredirect"
        first_seen = existing_auto_redirects.get(key, {}).get("first_seen")
        if not first_seen:
            first_seen = now.isoformat()
        updated[key] = {
            "url": url,
            "redirect": domain,
            "ca": "Cloudflare",
            "sslname": "miraheze-origin-cert",
            "first_seen": first_seen,
        }

    return updated


def filter_auto_redirects(auto_redirects: dict, now: datetime, wait_hours: int = REDIRECT_WAIT_HOURS) -> dict:
    """
    Return auto redirects that are older than wait_hours so that there is enough time for DNS propagation.
    Also remove the first_seen entry so that it complies to the format of the final yaml file.
    """
    filtered = {}
    for key, entry in auto_redirects.items():
        first_seen: datetime = datetime.fromisoformat(entry["first_seen"])
        if now - first_seen >= timedelta(hours=wait_hours):
            copied_entry = dict(entry)
            copied_entry.pop("first_seen")
            filtered[key] = copied_entry

    return filtered


def write_yaml_with_header(filename: str, header: str, data: dict, sort_keys=True) -> None:
    # Make sure the conversion works before trying to write to the file
    dumped = yaml.dump(data, sort_keys=sort_keys)
    yaml.safe_load(dumped)

    with open(filename, "w") as f:
        f.write(header)
        f.write(dumped)


def write_auto_redirects(auto_redirects: dict) -> None:
    write_yaml_with_header(REDIRECTS_AUTO_FILE, REDIRECTS_AUTO_HEADER, auto_redirects)


def write_redirects(manual_redirects: dict, auto_redirects: dict) -> None:
    manual_domains = get_domains_of(manual_redirects)
    merged = dict(manual_redirects)
    for key, entry in auto_redirects.items():
        if entry["url"] in manual_domains or entry["redirect"] in manual_domains:
            continue
        merged[key] = entry
    # Manual redirects first, auto next
    write_yaml_with_header(REDIRECTS_OUTPUT_FILE, REDIRECTS_HEADER, merged, sort_keys=False)


def sync_redirects(
        workdir: str,
        cf_domains: list[str],
        wd_domains: list[str],
        wd_yaml: dict,
        manual_redirects: dict,
        manual_domains: set[str],
        quiet: bool,
) -> list[str]:
    """
    Return list of all redirects derived from manual redirects + automatic redirects.
    """
    if not quiet:
        print("Updating auto-detected redirect candidates...")
    # Do this once and don't worry about the cwd for the rest of the function
    os.chdir(workdir)
    now = datetime.now(timezone.utc)
    candidates = get_auto_redirect_candidate_domains(cf_domains, wd_domains, manual_domains)
    existing_auto_redirects = load_yaml_file(REDIRECTS_AUTO_FILE, expect_exist=False)
    auto_redirects = update_auto_redirects(existing_auto_redirects, candidates, wd_yaml, now, manual_domains)
    filtered_auto_redirects = filter_auto_redirects(auto_redirects, now)

    if not quiet:
        print("Writing to redirects_auto.yaml and redirects.yaml...")
    write_auto_redirects(auto_redirects)
    write_redirects(manual_redirects, filtered_auto_redirects)

    auto_urls = set(entry["redirect"] for entry in auto_redirects.values())
    return list(manual_domains | auto_urls)


def write_files(workdir, cf_list=None, wd_yaml=None, wd_domains=None, redirect_list=None):
    os.chdir(workdir)

    if cf_list is not None:
        with open(CLOUDFLARE_OUTPUT, "w") as f:
            f.write("\n".join(cf_list))

    if wd_yaml is not None:
        with open(WIKIDISCOVER_OUTPUT, "w") as f:
            yaml.dump(wd_yaml, f, sort_keys=True)

    if cf_list is not None and wd_domains is not None:
        cf_set = set(cf_list)
        wd_set = set(wd_domains)
        exempt_set = set(EXEMPT_DOMAINS)

        only_in_cf = {domain for domain in cf_set if ".miraheze.org" not in domain}
        only_in_cf = only_in_cf - wd_set - exempt_set
        if redirect_list is not None:
            redirect_set = set(redirect_list)
            only_in_cf = only_in_cf - redirect_set
        only_in_wd = wd_set - cf_set

        with open(LOG_FILE, "w") as f:
            if only_in_cf:
                f.write("Domains in Cloudflare but not listed in WikiDiscover:\n")
                f.writelines(f"{domain}\n" for domain in sorted(only_in_cf))
            if only_in_wd:
                f.write("\nDomains listed in WikiDiscover but not in Cloudflare:\n")
                f.writelines(f"{domain}\n" for domain in sorted(only_in_wd))
            if not only_in_cf and not only_in_wd:
                f.write("All domains match between Cloudflare and WikiDiscover.\n")


def git_push(workdir):
    os.chdir(workdir)

    subprocess.run([
        "git", "config", "--global", "core.sshCommand",
        "ssh -i /var/lib/nagios/id_ed25519 -F /dev/null -o ProxyCommand='nc -X connect -x bastion.fsslc.wtnet:8080 %h %p'"
    ], check=True)

    subprocess.run(["git", "-C", workdir, "config", "user.name", "WikiTideBot"], check=True)
    subprocess.run(["git", "-C", workdir, "config", "user.email", "noreply@wikitide.org"], check=True)
    subprocess.run(["git", "add", CLOUDFLARE_OUTPUT, WIKIDISCOVER_OUTPUT, LOG_FILE, REDIRECTS_OUTPUT_FILE, REDIRECTS_AUTO_FILE], check=True)

    result = subprocess.run(["git", "diff", "--cached", "--quiet"])
    if result.returncode == 0:
        print("No changes to commit.")
        return

    subprocess.run(["git", "commit", "-m", "Bot: Auto-update domain lists"], check=True)
    subprocess.run(["git", "push", "origin"], check=True)


def main():
    parser = argparse.ArgumentParser(description="Fetch and compare domains from Cloudflare and WikiDiscover.")
    parser.add_argument("--workdir", type=str, default="/srv/ssl/ssl", help="Working directory containing the Git repo.")
    parser.add_argument("--dry-run", action="store_true", help="Do not push changes to Git.")
    parser.add_argument("--source", choices=["cloudflare", "wikidiscover", "all"], default="all", help="Which data sources to use.")
    parser.add_argument("--quiet", action="store_true", help="Suppress all console output.")

    args = parser.parse_args()

    # Validate working directory
    if not os.path.exists(args.workdir):
        print(f"Error: Working directory '{args.workdir}' does not exist!", file=sys.stderr)
        sys.exit(1)

    if not os.access(args.workdir, os.W_OK):
        print(f"Error: You do not have write permissions for '{args.workdir}'!", file=sys.stderr)
        sys.exit(1)

    # T15362: Temporarily enable GIT_TRACE
    env = os.environ.copy()
    env["GIT_TRACE"] = "1"
    subprocess.run(["git", "-C", args.workdir, "pull"], check=True, env=env)

    cf_domains = None
    wd_yaml = None
    wd_domains = None

    if args.source in ("cloudflare", "all"):
        if not args.quiet:
            print("Fetching Cloudflare domains...")
        cf_domains = get_cloudflare_domains(quiet=args.quiet)

    if args.source in ("wikidiscover", "all"):
        if not args.quiet:
            print("Fetching WikiDiscover data...")
        wd_yaml, wd_domains = get_wikidiscover_data()

    manual_redirects = load_yaml_file(os.path.join(args.workdir, REDIRECTS_MANUAL_FILE))
    manual_domains = get_domains_of(manual_redirects)
    redirect_list = manual_domains

    if args.source == "all":
        redirect_list = sync_redirects(args.workdir, cf_domains, wd_domains, wd_yaml, manual_redirects, manual_domains, args.quiet)

    if not args.quiet:
        print("Writing output files...")
    write_files(args.workdir, cf_domains, wd_yaml, wd_domains, redirect_list)

    if args.dry_run:
        if not args.quiet:
            print("Dry run enabled: skipping git push...")
    else:
        if not args.quiet:
            print("Pushing to GitHub...")
        git_push(args.workdir)

    if not args.quiet:
        print("Done!")

if __name__ == "__main__":
    main()
