#!/bin/bash

if [ $USER = 'root' ]
then
  ACTOR=$SUDO_USER
else
  ACTOR=$USER
fi

if [ "$HOSTNAME" == "mon111" ]; then
    echo '!log' "[$ACTOR@$HOSTNAME] $*" | nc -q0 -u 2a10:6740::6:205 5071
else
    echo '!log' "[$ACTOR@$HOSTNAME] $*" | nc -q0 -u 51.195.236.249 5071
fi
