# This file is generated by ModuleSync, do not edit.
require 'puppetlabs_spec_helper/module_spec_helper'

RSpec.configure do |c|
  c.filter_gems_from_backtrace 'rspec-puppet', 'puppet'
end

if Puppet.version.to_f >= 4.5
  RSpec.configure do |c|
    c.before :each do
      Puppet.settings[:strict] = :error
    end
  end
end

# put local configuration and setup into spec_helper_local
begin
  require 'spec_helper_local'
rescue LoadError
  puts 'error loading spec_helper_local'
end
