#!/bin/bash
#
# Renews LetsEncrypt cert
#
# This script is only compatible with LetsEncrypt
# do not try to use it with any other certs.
#
# Miraheze Staff 2018
set -e
set -u

function log {
    echo "$@"
}

function usage {
    echo "Usage: $0 [-h] [-s <state>] [-u <URL>]"
    echo "  -h      display help"
    echo "  -s      state of service like WARNING and OK"
    echo "  -u      URL ie <domain>"
    exit 1
}

while getopts ":hs:u:" option; do
    case $option in
        h)
            usage
            ;;
        s)
            STATE="$OPTARG"
            ;;
        u)
            URL="$OPTARG"
            ;;
        *)
            usage
            ;;
    esac
done

test -z ${STATE} && usage
test -z ${URL} && usage

case $STATE in
  OK)
    # It's all good
    ;;
  UNKNOWN)
    # We can't do anything about this really
    ;;
  WARNING)
    # Lets Renew here
    git config --global core.sshCommand "ssh -i /var/lib/nagios/id_rsa -F /dev/null"
    if [ ! -d /srv/ssl/ssl/ ]; then
      cd /srv/ssl/ && git clone git@github.com:miraheze/ssl.git
    else
            cd /srv/ssl/ssl && git reset --hard origin/master && git pull
    fi
    git -C /srv/ssl/ssl/ config user.email "noreply@miraheze.org"
    git -C /srv/ssl/ssl/ config user.name "MirahezeSSLBot"
    sudo /root/ssl-certificate -r $URL > /srv/ssl/ssl/certificates/$URL.crt
    sed -i "/Re-generating a new SSL cert for ${URL}/d" /srv/ssl/ssl/certificates/$URL.crt
    sed -i "/LetsEncrypt certificate at: \/root\/ssl\/${URL}.crt/d" /srv/ssl/ssl/certificates/$URL.crt
    git -C /srv/ssl/ssl add /srv/ssl/ssl/certificates/$URL.crt
    git -C /srv/ssl/ssl/ commit -m "Bot: Update SSL cert for ${URL}"
    git -C /srv/ssl/ssl/ push origin master
    ;;
  CRITICAL)
    # If the above failed, let's not act here. CRITICAL is human intervention time
    echo "CRITICAL - FAIL SAFE"
    ;;
esac

exit 0
