# Any changes done in here will need /usr/local/bin/opensearch-security ran afterwards
# to apply it. This config file isn't directly read rather the script ran inside opensearch-security
# reads the config and inserts it into the index which os-security reads.

_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: true
