fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: v4.13.0
    provision: 'https://github.com/puppetlabs/provision.git'
  symlinks:
    stdlib: "#{source_dir}"
    test:   "#{source_dir}/spec/fixtures/test"