---
.travis.yml:
  addons:
    apt:
      sources:
        - augeas
      packages:
        - libaugeas-dev
  acceptance:
    - '*'
  includes:
    -
      bundler_args:
      env: PLATFORMS=centos6
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/centos6]'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args:
      env: PLATFORMS=centos7
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/centos7]'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args:
      env: PLATFORMS=debian8
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/debian8]'
        - bundle exec bolt command run 'apt-get install lsb-release gnupg iproute2 -y' --inventoryfile inventory.yaml --nodes='localhost*'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args:
      env: PLATFORMS=debian9
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/debian9]'
        - bundle exec bolt command run 'apt-get install lsb-release gnupg iproute2 -y' --inventoryfile inventory.yaml --nodes='localhost*'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args:
      env: PLATFORMS=ubuntu16.04
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/ubuntu16.04]'
        - bundle exec bolt command run 'apt-get install lsb-release gnupg iproute2 -y' --inventoryfile inventory.yaml --nodes='localhost*'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args:
      env: PLATFORMS=ubuntu18.04
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/ubuntu18.04]'
        - bundle exec bolt command run 'apt-get install lsb-release gnupg iproute2 -y' --inventoryfile inventory.yaml --nodes='localhost*'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
  allow_failures:
    -
      bundler_args:
      env: PLATFORMS=centos7
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/centos7]'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
  user: camptocamp
  secure: "ZjmgM4a2tcCE4dtccVSmYZAcuCaXdZNsZxVzRiDg7URBYyALMNgCV6XaiS/DTHX4jCuiyw/89Vywyf+uDjrj1552D+lF3cuQMXziwJhXp9v0jJRT9kpq8CFnq4iC/qwqLj54QIhIFoVgtiY9k+2MWRoMuGveLnAmg9K6wSNvLS4="
  branches:
    - master
    - /^\d/
  deploy_to_forge:
    enabled: true
    tag_regex: "^\\d"

Gemfile:
  required:
    ':development':
      - gem: ruby-augeas
  optional:
    ':development':
      - gem: 'github_changelog_generator'

Rakefile:
  changelog_version_tag_pattern: '%s'

spec/spec_helper.rb:
  spec_overrides:
    - |-
      # There's no real need to make this version dependent, but it helps find
      # regressions in Puppet
      #
      # 1. Workaround for issue #16277 where default settings aren't initialised from
      # a spec and so the libdir is never initialised (3.0.x)
      # 2. Workaround for 2.7.20 that now only loads types for the current node
      # environment (#13858) so Puppet[:modulepath] seems to get ignored
      # 3. Workaround for 3.5 where context hasn't been configured yet,
      # ticket https://tickets.puppetlabs.com/browse/MODULES-823
      #
      require 'pathname'
      dir = Pathname.new(__FILE__).parent
      ver = Gem::Version.new(Puppet.version.split('-').first)
      if ver >= Gem::Version.new('2.7.20')
        puts 'augeasproviders: setting $LOAD_PATH to work around broken type autoloading'
        Puppet.initialize_settings
        $LOAD_PATH.unshift(
          dir,
          File.join(dir, 'fixtures/modules/augeasproviders_core/spec/lib'),
          File.join(dir, 'fixtures/modules/augeasproviders_core/lib'),
        )
        $LOAD_PATH.unshift(File.join(dir, '..', 'lib'))
      end

.rubocop.yml:
  selected_profile: off

