fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    archive: https://github.com/voxpupuli/puppet-archive.git
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core.git
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    datacat: https://github.com/richardc/puppet-datacat.git
    elastic_stack: https://github.com/voxpupuli/puppet-elastic_stack.git
    java: https://github.com/puppetlabs/puppetlabs-java.git
    java_ks: https://github.com/puppetlabs/puppetlabs-java_ks.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
    zypprepo: https://github.com/voxpupuli/puppet-zypprepo.git
