# class base::syslog
class base::syslog (
        String $syslog_daemon = lookup('base::syslog::syslog_daemon', {'default_value' => 'syslog_ng'}),
    ) {
        if $syslog_daemon == 'rsyslog' {
                include ::rsyslog

                file { '/etc/rsyslog.conf':
                    ensure => present,
                    source => 'puppet:///modules/base/rsyslog/rsyslog.conf',
                    notify => Service['rsyslog'],
                }
        } elsif $syslog_daemon == 'syslog_ng' {
                package { 'rsyslog':
                    ensure  => purged,
                } ->
                class { '::syslog_ng':
                        config_file_header      => "# This file was generated by Puppet's ccin2p3-syslog_ng module\n@version: 3.19",
                        manage_init_defaults    => false,
                        manage_repo             => false, # Is the default, but explicitly defined now
                } ->
                syslog_ng::options { 'global_options':
                        options     => {
                                'chain_hostnames'       => 'off',
                                'flush_lines'           => 0,
                                'stats_freq'            => 0,
                                'use_dns'               => 'no',
                                'use_fqdn'              => 'yes',
                                'dns_cache'             => 'no',
                        },
                } ->
                syslog_ng::rewrite { 'r_hostname':
                        params => {
                                'type'      => 'set',
                                'options'   => [
                                        $::fqdn,
                                        { 'value' => 'HOST' }
                                ],
                        },
                } ->
                syslog_ng::source { 's_src_system':
                        params => {
                                'type'          => 'system',
                                'options'       => [],
                        },
                } ->
                syslog_ng::source { 's_src_internal':
                        params => {
                                'type'          => 'internal',
                                'options'       => [],
                        },
                } ->
                syslog_ng::source { 's_src_udp_local':
                        params => {
                                'type'          => 'syslog',
                                'options'       => [
                                        { 'transport'   => 'udp' },
                                        { 'port'        => 10514 },
                                ],
                        }
                } ->
                syslog_ng::destination { 'd_graylog_syslog_tls':
                        params => {
                                type    => 'syslog',
                                options => [
                                        "graylog1.miraheze.org",
                                        { 
                                                'port' => [ 12210 ] 
                                        },
                                        { 
                                                'transport' => 'tls' 
                                        },
                                        {
                                                'tls' => [
                                                        { 
                                                                'peer-verify' => 'required-trusted' 
                                                        },
                                                        { 
                                                                'ca-dir' => '/etc/ssl/certs' 
                                                        },
                                                        {       
                                                                'ssl-options' => [ 'no-sslv2', 'no-sslv3', 'no-tlsv1', 'no-tlsv11' ] 
                                                        }
                                                ]
                                        },
                                        {
                                                'disk-buffer' => [
                                                        { 
                                                                'dir' => '/var/tmp' 
                                                        },
                                                        { 
                                                                'disk-buf-size' => '1073741824' 
                                                        },
                                                        { 
                                                                'mem-buf-size' => '33554432' 
                                                        },
                                                        { 
                                                                'reliable' => 'yes' 
                                                        }
                                                ]
                                        },
                                ],
                        },
                } ->
                syslog_ng::log { 's_src_system to d_graylog_syslog_tls':
                        params => [
                                { 
                                        'source' => 's_src_system' 
                                },
                                { 
                                        'destination' => 'd_graylog_syslog_tls' 
                                },
                        ],
                } ->
                syslog_ng::log { 's_src_internal to d_graylog_syslog_tls':
                        params => [
                                { 
                                        'source' => 's_src_internal' 
                                },
                                { 
                                        'destination' => 'd_graylog_syslog_tls' 
                                },
                        ],
                } ->
                syslog_ng::log { 's_src_udp_local to d_graylog_syslog_tls':
                    params => [
                        {
                            'source' => 's_src_udp_local',
                        },
                        {
                            'rewrite' => 'r_hostname',
                        },
                        {
                            'destination' => 'd_graylog_syslog_tls',
                        },
                    ],
                }
        } else {
                warning('Invalid syslog_daemon selected for base::syslog.')
        }
}
