#!/bin/bash
set -u
/usr/sbin/icinga2 daemon -C > /dev/null 2>&1
RETVAL=$?
if [ ${RETVAL} -eq 0 ]; then
    echo "Icinga configuration is correct"
    exit 0
fi;
echo "Icinga configuration contains errors"
exit 2
