#!ruby
source 'https://rubygems.org'

group :development, :test do
  gem "rake", ">= 12.3.3"
  gem 'puppetlabs_spec_helper', :require => false
  gem 'puppet-lint'
end

group :integration do
  gem 'test-kitchen'
  gem 'kitchen-docker'
  gem 'kitchen-inspec'
  gem 'kitchen-puppet'
end
if puppetversion = ENV['PUPPET_GEM_VERSION']
  gem 'puppet', puppetversion, :require => false
else
  gem 'puppet', :require => false
end
