fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    yum: https://github.com/voxpupuli/puppet-yum.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
    zypprepo: https://github.com/voxpupuli/puppet-zypprepo.git
