# SPDX-License-Identifier: Apache-2.0
fixtures:
    symlinks:
        httpd: "#{source_dir}"
        stdlib: "../../../../stdlib"
        systemd: "../../../../systemd"
        wmflib: "../../../../wmflib"
