#!/bin/bash
# icinga check monitoring the job queue

while read total count
do
        if [ ! $(echo "$count" | grep -E "^[0-9]+$") ]; then
                echo "JOBQUEUE CRITICAL - check plugin (`basename $0`) or PHP errors"
                exit 2
        elif [ $count -gt 300 ]; then
                echo "JOBQUEUE CRITICAL - job queue greater than 300 jobs. Current queue: $count"
                exit 2
        else
                echo "JOBQUEUE OK - job queue below 300 jobs"
                exit 0
        fi
done < <( /usr/bin/php5 /srv/mediawiki/w/extensions/MirahezeMagic/maintenance/getJobQueueLengths.php --totalonly --wiki loginwiki)
