fixtures:
  forge_modules:
    stdlib:
      repo: icinga/icinga
    stdlib:
      repo: puppetlabs/stdlib
      ref: 5.2.0
    concat:
      repo: puppetlabs/concat
      ref: 5.3.0
    apt:
      repo: puppetlabs/apt
      ref: 6.3.0
    chocolatey:
      repo: puppetlabs/chocolatey
      ref: 3.3.0
    zypprepo:
      repo: puppet/zypprepo
      ref: 2.2.2
