# Version compatibility for Puppet 3
fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    concat:
      repo: "puppetlabs/concat"
      ref: "2.2.1"
    apt:
      repo: "puppetlabs/apt"
      ref: "2.4.0"
    chocolatey: "puppetlabs/chocolatey"
    zypprepo: "puppet/zypprepo"
  symlinks:
    icinga2: "#{source_dir}"
