---
fixtures:
  repositories:
    icinga: https://github.com/voxpupuli/puppet-icinga
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    concat: https://github.com/puppetlabs/puppetlabs-concat
    apt: https://github.com/puppetlabs/puppetlabs-apt
    chocolatey: https://github.com/puppetlabs/puppetlabs-chocolatey
    zypprepo: https://github.com/voxpupuli/puppet-zypprepo
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core
