fixtures:
  forge_modules:
    icinga:
      repo: icinga/icinga
    stdlib:
      repo: puppetlabs/stdlib
    concat:
      repo: puppetlabs/concat
    apt:
      repo: puppetlabs/apt
    chocolatey:
      repo: puppetlabs/chocolatey
    zypprepo:
      repo: puppet/zypprepo
    yumrepo_core:
      repo: puppetlabs-yumrepo_core
      puppet_version: ">= 6.0.0"

