fixtures:
  repositories:
     apt: 'https://github.com/puppetlabs/puppetlabs-apt.git'
     translate: 'https://github.com/puppetlabs/puppetlabs-translate.git'
     stdlib:
       repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
       ref: 4.6.0
     concat:
       repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
       ref: 2.0.0
#  symlinks:
#    patterndb: "#{source_dir}"
