"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://meta.miraheze.org
  name = meta

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'miraheze'
    langs = {
        'meta': 'meta.miraheze.org',
        'test': 'test.miraheze.org',
    }

    def scriptpath(self, code):
        return {
            'meta': '/w',
            'test': '/w',
        }[code]

    def protocol(self, code):
        return {
            'meta': 'https',
            'test': 'https',
        }[code]