---
HOSTS:
  ubuntu1604-64-1:
    pe_dir:
    pe_ver:
    pe_upgrade_dir:
    pe_upgrade_ver:
    hypervisor: vmpooler
    platform: ubuntu-16.04-amd64
    packaging_platform: ubuntu-16.04-amd64
    template: ubuntu-1604-x86_64
    roles:
      - agent
      - default
CONFIG:
  type: agent
  nfs_server: none
  consoleport: 443
  pooling_api: http:vmpooler.delivery.puppetlabs.net/
